title: Make documentation at ease!
basePath: src
rootContent: what-is-fluorite.md
contentAssets:
  assets/contents: /
exclusions:
  - CNAME
outputDir: ../../fluorite-gh-pages
blueprint: !!import/single ./blueprint.yaml
rendererOptions:
  theme: elegance
  multiPage: true
  versions:
    - "1.1.0"
    - "1.2.0"
    - "1.3.3"
    - "1.3.8"
    - "1.4.0"
themeOptions:
  brandName: Fluorite
  icon: src/assets/theme/logo.svg
  favicon: src/assets/theme/favicon.ico
  rootName: Introduction
  hideProgressBar: false
  noSectionTitles: false
  accentColor: "#8670b2"
  accentColorSecondary: "#bc6cc1"